[phases.setup]
# Solo necesitamos Python, ¡adiós a las librerías gráficas problemáticas!
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'Building Backend...'"]

[start]
cmd = ". /opt/venv/bin/activate && cd backend && gunicorn config.wsgi:application"