# Generated by Django 5.2.11 on 2026-02-12 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT personal', max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_semanales', models.DecimalField(decimal_places=1, default=44.0, help_text='Ej: 40.0, 44.0, 45.0', max_digits=3)),
                ('distribucion_dias', models.IntegerField(default=5, help_text='Días de trabajo a la semana (Ej: 5 o 6)')),
                ('tipo_jornada', models.CharField(choices=[('ORDINARIA', 'Ordinaria (Lunes a Viernes/Sábado)'), ('BISMANAL', 'Bismanal'), ('ART_22', 'Artículo 22 (Sin horario)'), ('PARCIAL', 'Part-Time')], default='ORDINARIA', max_length=20)),
                ('sueldo_base', models.IntegerField()),
                ('tiene_colacion_imputable', models.BooleanField(default=False, help_text='¿El tiempo de colación es parte de la jornada?')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_activo', to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_legal', models.CharField(max_length=255)),
                ('rut', models.CharField(help_text='RUT de la empresa sin puntos', max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('giro', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('empresa', 'rut')},
        ),
    ]
