# Generated by Django 5.2.11 on 2026-02-24 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='giro',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='empleado',
            name='afp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='comuna',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='modalidad',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto'), ('HIBRIDO', 'Híbrido')], default='PRESENCIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nacionalidad',
            field=models.CharField(default='Chilena', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sistema_salud',
            field=models.CharField(blank=True, choices=[('FONASA', 'Fonasa'), ('ISAPRE', 'Isapre')], max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sueldo_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rut',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rut',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='telefono',
        ),
    ]
