# Generated by Django 5.2.11 on 2026-02-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_alias_empresa_ciudad_empresa_comuna_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='apellidos',
            new_name='apellido_paterno',
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horas_laborales',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='afp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sistema_salud',
            field=models.CharField(blank=True, choices=[('FONASA', 'Fonasa'), ('ISAPRE', 'Isapre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sucursal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
