# Generated by Django 5.2.11 on 2026-03-10 04:25

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_plan_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='max_empleados',
            new_name='limite_trabajadores',
        ),
        migrations.AddField(
            model_name='contrato',
            name='cargo',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AddField(
            model_name='contrato',
            name='clausulas_especiales',
            field=models.TextField(blank=True, help_text='Pactos de teletrabajo, confidencialidad, bonos, etc.', null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='jornada_personalizada',
            field=models.TextField(blank=True, help_text="Se usa solo si eligen 'OTRO' en jornada", null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('PLAZO_FIJO', 'Plazo Fijo'), ('OBRA_FAENA', 'Por Obra o Faena')], default='INDEFINIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='distribucion_dias',
            field=models.IntegerField(default=5, help_text='Días a la semana (Ej: 5 o 6)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='horas_semanales',
            field=models.DecimalField(decimal_places=1, default=44.0, help_text='Ej: 40.0, 44.0', max_digits=3),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tiene_colacion_imputable',
            field=models.BooleanField(default=False, help_text='¿Colación dentro de la jornada?'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_jornada',
            field=models.CharField(choices=[('ORDINARIA', 'Ordinaria (Lunes a Viernes/Sábado)'), ('TURNOS', 'Turnos Rotativos'), ('BISMANAL', 'Bismanal'), ('ART_22', 'Artículo 22 (Sin límite de horario)'), ('PARCIAL', 'Part-Time'), ('OTRO', 'Otra (Jornada Personalizada)')], default='ORDINARIA', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='empresa',
            unique_together={('rut', 'owner')},
        ),
    ]
