# Generated by Django 5.2.11 on 2026-03-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_max_empleados_plan_limite_trabajadores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='tiene_colacion_imputable',
        ),
        migrations.AddField(
            model_name='contrato',
            name='dia_pago',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='contrato',
            name='dia_quincena',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='distribucion_horario',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='funciones_especificas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='gratificacion_legal',
            field=models.CharField(choices=[('MENSUAL', 'Mensual (Art. 50)'), ('ANUAL', 'Anual (Art. 47)')], default='MENSUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='contrato',
            name='monto_quincena',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tiene_quincena',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='clausulas_especiales',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='distribucion_dias',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='horas_semanales',
            field=models.DecimalField(decimal_places=1, default=44.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='jornada_personalizada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
