# Generated by Django 5.2.11 on 2026-03-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_contrato_tiene_colacion_imputable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rut_representante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
