# Generated by Django 5.2.11 on 2026-03-10 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empresa_representante_legal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AMONESTACION', 'Carta de Amonestación'), ('DESPIDO', 'Carta de Término de Contrato (Despido)'), ('MUTUO_ACUERDO', 'Renuncia / Mutuo Acuerdo'), ('CONSTANCIA', 'Constancia Laboral')], max_length=20)),
                ('fecha_emision', models.DateField()),
                ('causal_legal', models.CharField(blank=True, max_length=255, null=True)),
                ('hechos', models.TextField()),
                ('aviso_previo_pagado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_legales', to='core.empleado')),
            ],
        ),
    ]
