# Generated by Django 5.2.11 on 2026-03-11 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_documentolegal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('dias_trabajados', models.IntegerField(default=30)),
                ('sueldo_base', models.IntegerField(default=0)),
                ('gratificacion', models.IntegerField(default=0)),
                ('bonos_imponibles', models.IntegerField(default=0)),
                ('haberes_no_imponibles', models.IntegerField(default=0)),
                ('afp_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('afp_monto', models.IntegerField(default=0)),
                ('salud_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('salud_monto', models.IntegerField(default=0)),
                ('seguro_cesantia', models.IntegerField(default=0)),
                ('impuesto_unico', models.IntegerField(default=0)),
                ('anticipo_quincena', models.IntegerField(default=0)),
                ('total_imponible', models.IntegerField(default=0)),
                ('total_haberes', models.IntegerField(default=0)),
                ('total_descuentos', models.IntegerField(default=0)),
                ('sueldo_liquido', models.IntegerField(default=0)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='core.empleado')),
            ],
            options={
                'unique_together': {('empleado', 'mes', 'anio')},
            },
        ),
    ]
