# Generated by Django 5.2.11 on 2026-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_liquidacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion',
            name='bonos_imponibles',
        ),
        migrations.RemoveField(
            model_name='liquidacion',
            name='haberes_no_imponibles',
        ),
        migrations.AddField(
            model_name='empleado',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='centro_costo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ficha_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='forma_pago',
            field=models.CharField(default='Transferencia', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='plan_isapre_uf',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='detalle_haberes_imponibles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='detalle_haberes_no_imponibles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='detalle_horas_extras',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='detalle_otros_descuentos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='dias_ausencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='dias_licencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='dias_no_contratados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='isapre_cotizacion_uf',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
