# Generated by Django 5.2.11 on 2026-03-14 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_empleado_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('TRIAL', 'Período de Prueba'), ('ACTIVE', 'Activa'), ('PAST_DUE', 'Pago Pendiente / Moroso'), ('CANCELED', 'Cancelada')], default='TRIAL', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_proximo_cobro', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('gateway_customer_id', models.CharField(blank=True, help_text='ID del cliente en la pasarela', max_length=100, null=True)),
                ('gateway_subscription_id', models.CharField(blank=True, help_text='ID de la suscripción/tarjeta', max_length=100, null=True)),
                ('metodo_pago_glosa', models.CharField(blank=True, help_text='Ej: Visa terminada en 4242 o Fintoc Banco de Chile', max_length=50, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion_activa', to='core.cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan')),
            ],
        ),
    ]
