# Generated by Django 5.2.11 on 2026-03-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cliente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ficha_numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Ficha'),
        ),
    ]
