# Generated by Django 5.2.11 on 2026-04-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_empleado_ficha_numero'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='empresa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
