# Generated by Django 5.2.11 on 2026-04-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_empresa_unique_together_empresa_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='archivo_anexo_40h',
            field=models.FileField(blank=True, null=True, upload_to='anexos/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='archivo_contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
        migrations.AddField(
            model_name='documentolegal',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos_legales/'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='liquidaciones/'),
        ),
    ]
