# Generated by Django 5.2.13 on 2026-07-21 15:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_plan_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='sueldo_base',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='horas_laborales',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo_base',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='dias_ausencia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='dias_licencia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='dias_no_contratados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='dias_trabajados',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limite_trabajadores',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='solicitudfirma',
            name='finiquito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.finiquito'),
        ),
    ]