# Generated by Django 5.2.13 on 2026-07-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_contrato_es_profesional_titulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudfirma',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de firma'), ('PROCESANDO', 'Procesando firma'), ('FIRMADO', 'Firmado'), ('RECHAZADO', 'Rechazado por el trabajador'), ('EXPIRADO', 'Plazo vencido'), ('CANCELADO', 'Cancelado por el empleador')], default='PENDIENTE', max_length=12),
        ),
    ]