# Generated by Django 5.2.17 on 2026-09-23 13:14

import core.jornada
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_parametros_historicos_2024_2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="horas_semanales",
            field=models.DecimalField(
                decimal_places=1,
                default=core.jornada.jornada_maxima_por_defecto,
                max_digits=3,
            ),
        ),
    ]
