# Generated by Django 5.2.17 on 2026-09-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_contrato_horas_por_defecto_vigente"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidacion",
            name="horas_semanales_contrato",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
    ]
