# Generated by Django 5.2.17 on 2026-09-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_liquidacion_horas_semanales_congeladas"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametroprevisional",
            name="tasa_afc_empleador_11_anios",
            field=models.DecimalField(decimal_places=5, default=0.008, max_digits=6),
        ),
        migrations.AddField(
            model_name="parametroprevisional",
            name="tasa_afp_empleador",
            field=models.DecimalField(decimal_places=5, default=0.001, max_digits=6),
        ),
        migrations.AddField(
            model_name="parametroprevisional",
            name="tasa_rentabilidad_protegida",
            field=models.DecimalField(decimal_places=5, default=0.009, max_digits=6),
        ),
        migrations.AlterField(
            model_name="parametroprevisional",
            name="tasa_expectativa_vida",
            field=models.DecimalField(decimal_places=5, default=0.0072, max_digits=6),
        ),
    ]
