# Generated by Django 5.2.17 on 2026-09-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_parametros_previred_septiembre_2026"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudfirma",
            name="folio",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="solicitudfirma",
            name="hash_firmado",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="solicitudfirma",
            name="hash_original",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
