# Generated by Django 5.2.17 on 2026-09-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_comprobante_firma"),
    ]

    operations = [
        migrations.AddField(
            model_name="finiquito",
            name="aviso_previo_dado",
            field=models.BooleanField(default=False),
        ),
    ]
