# Generated by Django 5.2.17 on 2026-09-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_planes_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoPasarela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evento", models.CharField(max_length=60)),
                (
                    "gateway_subscription_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "orden_compra",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("monto", models.IntegerField(default=0)),
                ("fecha_pago", models.DateField(blank=True, null=True)),
                ("datos", models.JSONField(blank=True, default=dict)),
                (
                    "aplicado",
                    models.BooleanField(
                        default=False,
                        help_text="Si ya se reflejó en la suscripción del cliente.",
                    ),
                ),
                ("recibido_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_pasarela",
                        to="core.cliente",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de la pasarela",
                "verbose_name_plural": "Eventos de la pasarela",
                "ordering": ["-recibido_en"],
            },
        ),
    ]
