# Generated by Django 5.2.17 on 2026-09-24 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_evento_pasarela"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="cargas_invalidas",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="cargas_maternales",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="cargas_simples",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(13)]
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="isapre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Banmédica"),
                    ("02", "Consalud"),
                    ("03", "Vida Tres"),
                    ("04", "Colmena"),
                    ("05", "Cruz Blanca"),
                    ("10", "Nueva Masvida"),
                    ("11", "Isalud"),
                    ("12", "Fundación"),
                    ("25", "Cruz del Norte"),
                    ("28", "Esencial"),
                ],
                default="",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="numero_fun",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tramo_asignacion_familiar",
            field=models.CharField(
                choices=[
                    ("A", "Primer tramo"),
                    ("B", "Segundo tramo"),
                    ("C", "Tercer tramo"),
                    ("D", "Sin derecho"),
                ],
                default="D",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="ccaf",
            field=models.CharField(
                choices=[
                    ("00", "Sin caja de compensación"),
                    ("01", "Los Andes"),
                    ("02", "La Araucana"),
                    ("03", "Los Héroes"),
                    ("04", "18 de Septiembre"),
                ],
                default="00",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="mutual",
            field=models.CharField(
                choices=[
                    ("00", "ISL (sin mutual)"),
                    ("01", "Asociación Chilena de Seguridad (ACHS)"),
                    ("02", "Mutual de Seguridad CChC"),
                    ("03", "Instituto de Seguridad del Trabajo (IST)"),
                ],
                default="00",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="sucursal_mutual",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tasa_accidentes",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=6, null=True
            ),
        ),
    ]
