# Generated by Django 5.2.17 on 2026-09-24 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_datos_previred"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="anios_previos_feriado",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(10)]
            ),
        ),
    ]
