# Generated by Django 5.2.17 on 2026-09-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_consolidar_planes"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="fecha_desvinculacion",
            field=models.DateField(blank=True, null=True),
        ),
    ]
