# Generated by Django 5.2.17 on 2026-09-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_fecha_desvinculacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="precio_anual",
            field=models.IntegerField(default=0),
        ),
    ]
