# Generated by Django 5.2.17 on 2026-09-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_precio_anual_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suscripcion",
            name="ciclo",
            field=models.CharField(
                choices=[("MENSUAL", "Mensual"), ("ANUAL", "Anual")],
                default="MENSUAL",
                max_length=10,
            ),
        ),
    ]
