# Generated by Django 5.2.17 on 2026-09-25 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_suscripcion_ciclo"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntentoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ciclo",
                    models.CharField(
                        choices=[("MENSUAL", "Mensual"), ("ANUAL", "Anual")],
                        default="MENSUAL",
                        max_length=10,
                    ),
                ),
                (
                    "gateway_subscription_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos_pago",
                        to="core.cliente",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.plan"
                    ),
                ),
            ],
            options={
                "verbose_name": "Intento de pago",
                "verbose_name_plural": "Intentos de pago",
                "ordering": ["-creado_en"],
            },
        ),
    ]
