# Generated by Django 5.2.17 on 2026-09-25 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_intento_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="suscripcion",
            name="plan_programado",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan que rige desde el próximo cobro (bajada de plan).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.plan",
            ),
        ),
    ]
