# Generated by Django 5.2.17 on 2026-09-25 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_suscripcion_plan_programado"),
    ]

    operations = [
        migrations.AddField(
            model_name="anexocontrato",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("GENERAL", "Modificación del contrato"),
                    (
                        "CONSENTIMIENTO_ELECTRONICO",
                        "Autorización de documentación electrónica",
                    ),
                ],
                default="GENERAL",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="consentimiento_electronico_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="consentimiento_electronico_via",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONTRATO", "Cláusula del contrato"),
                    ("ANEXO", "Anexo firmado"),
                    ("PAPEL", "Firmado en papel"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="discapacidad",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empleado",
            name="pension_invalidez",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="solicitudfirma",
            name="incluye_consentimiento",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="RegistroDT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=40)),
                ("registrado_en", models.DateField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_dt",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "clave"), name="registro_dt_unico"
                    )
                ],
            },
        ),
    ]
