# Generated by Django 5.2.17 on 2026-09-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_registro_dt_y_consentimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="pensionado_vejez",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tecnico_extranjero_exento",
            field=models.BooleanField(
                default=False,
                help_text="Técnico extranjero exento de cotizar (Ley 18.156).",
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tipo_impuesto_renta",
            field=models.CharField(
                choices=[
                    ("1", "Impuesto de segunda categoría"),
                    ("2", "Impuesto único obrero agrícola"),
                    ("3", "Impuesto adicional"),
                ],
                default="1",
                max_length=1,
            ),
        ),
    ]
