# Generated by Django 5.2.17 on 2026-09-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_codigos_lre_catalogo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TramoAsignacionFamiliar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigente_desde", models.DateField()),
                (
                    "tramo",
                    models.CharField(
                        choices=[
                            ("A", "Primer tramo"),
                            ("B", "Segundo tramo"),
                            ("C", "Tercer tramo"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "monto",
                    models.PositiveIntegerField(
                        help_text="Monto mensual por carga (las cargas por invalidez reciben el doble)."
                    ),
                ),
                (
                    "renta_hasta",
                    models.PositiveIntegerField(
                        help_text="Ingreso mensual máximo del beneficiario para este tramo."
                    ),
                ),
                ("fuente", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "verbose_name": "Tramo de asignación familiar",
                "verbose_name_plural": "Tramos de asignación familiar",
                "ordering": ["-vigente_desde", "tramo"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vigente_desde", "tramo"), name="tramo_af_unico"
                    )
                ],
            },
        ),
    ]
