# Generated by Django 5.2.17 on 2026-09-28 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_seed_tramos_asignacion_familiar"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoTrabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rut", models.CharField(db_index=True, max_length=12)),
                ("huella", models.CharField(max_length=64)),
                ("correos", models.JSONField(default=list)),
                ("intentos", models.PositiveSmallIntegerField(default=0)),
                ("usado", models.BooleanField(default=False)),
                ("expira_en", models.DateTimeField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CuentaTrabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        help_text="RUT sin puntos ni guion (limpio).",
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("password", models.CharField(blank=True, default="", max_length=128)),
                ("invitacion_clave_vista", models.BooleanField(default=False)),
                ("version_sesion", models.PositiveIntegerField(default=1)),
                ("ultimo_ingreso", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CorreoTrabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("verificado_en", models.DateTimeField(auto_now=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correos",
                        to="core.cuentatrabajador",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cuenta", "email"), name="correo_trabajador_unico"
                    )
                ],
            },
        ),
    ]
