# Generated by Django 5.2.17 on 2026-09-28 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_portal_trabajador"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LIQUIDACION", "Liquidación de sueldo"),
                            ("FINIQUITO", "Finiquito"),
                            ("OTRO", "Otro documento"),
                        ],
                        max_length=12,
                    ),
                ),
                ("mes", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("anio", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("detalle", models.CharField(blank=True, default="", max_length=300)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("RESUELTA", "Resuelta"),
                            ("DESCARTADA", "Descartada"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Por qué se descartó (lo ve el trabajador).",
                        max_length=300,
                    ),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("resuelta_en", models.DateTimeField(blank=True, null=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes",
                        to="core.cuentatrabajador",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_documento",
                        to="core.empleado",
                    ),
                ),
            ],
            options={
                "ordering": ["-creada_en"],
            },
        ),
    ]
