# Generated by Django 5.2.17 on 2026-09-28 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_solicitud_documento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicituddocumento",
            name="detalle",
        ),
        migrations.AddField(
            model_name="solicituddocumento",
            name="vacacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_documento",
                to="core.vacacionempleado",
            ),
        ),
        migrations.AlterField(
            model_name="solicituddocumento",
            name="motivo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENTREGADO_PAPEL", "Se te entregó en papel."),
                    ("SIN_REMUNERACION", "Ese mes no hubo remuneración que liquidar."),
                    (
                        "FUERA_DE_RELACION",
                        "El período no corresponde a tu relación laboral.",
                    ),
                    (
                        "NO_CORRESPONDE",
                        "El documento no corresponde a tu situación laboral.",
                    ),
                ],
                default="",
                help_text="Por qué se descartó (lo ve el trabajador).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="solicituddocumento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("LIQUIDACION", "Liquidación de sueldo"),
                    ("CONTRATO", "Contrato de trabajo"),
                    ("ANEXO_40H", "Anexo Ley 40 horas"),
                    ("VACACION", "Comprobante de vacaciones"),
                    ("FINIQUITO", "Finiquito"),
                ],
                max_length=12,
            ),
        ),
    ]
