# Generated by Django 5.2.17 on 2026-09-28 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_solicitud_documento_cerrada"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificadoEmitido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ANTIGUEDAD", "Certificado de antigüedad laboral"),
                            ("RENTA", "Certificado de renta"),
                            ("VACACIONES", "Certificado de vacaciones"),
                            ("JORNADA", "Certificado de jornada y horario"),
                            ("TERMINO", "Certificado de término de relación laboral"),
                            ("COTIZACIONES", "Certificado de cotizaciones declaradas"),
                        ],
                        max_length=15,
                    ),
                ),
                ("opcion", models.CharField(blank=True, default="", max_length=10)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código de verificación impreso en el PDF.",
                        max_length=14,
                        unique=True,
                    ),
                ),
                ("datos", models.JSONField(default=dict)),
                ("emitido_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificados",
                        to="core.cuentatrabajador",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="core.empleado",
                    ),
                ),
            ],
            options={
                "ordering": ["-emitido_en"],
            },
        ),
    ]
