# Generated by Django 5.2.17 on 2026-09-28 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_certificados"),
    ]

    operations = [
        migrations.AddField(
            model_name="anexocontrato",
            name="datos",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="anexocontrato",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("GENERAL", "Modificación del contrato"),
                    (
                        "CONSENTIMIENTO_ELECTRONICO",
                        "Autorización de documentación electrónica",
                    ),
                    ("TELETRABAJO", "Pacto de trabajo a distancia o teletrabajo"),
                ],
                default="GENERAL",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfirma",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("CONTRATO", "Contrato Laboral"),
                    ("ANEXO_40H", "Anexo Ley 40 Horas"),
                    ("AMONESTACION", "Carta de Amonestación"),
                    ("DESPIDO", "Carta de Despido"),
                    ("CONSTANCIA", "Constancia Laboral"),
                    ("ANEXO_CONTRATO", "Anexo de Contrato"),
                    ("LIQUIDACION", "Liquidación de Sueldo"),
                    ("VACACION", "Comprobante de Vacaciones"),
                    ("FINIQUITO", "Finiquito de Término"),
                    ("HORAS_EXTRA", "Pacto de horas extraordinarias"),
                    ("DESCUENTO", "Autorización de descuento"),
                    ("PERMISO_LEGAL", "Constancia de permiso legal"),
                    ("INDEMNIZACION", "Pacto de indemnización a todo evento"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DocumentoLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("HORAS_EXTRA", "Pacto de horas extraordinarias"),
                            ("DESCUENTO", "Autorización de descuento"),
                            ("PERMISO_LEGAL", "Constancia de permiso legal con goce"),
                            ("INDEMNIZACION", "Pacto de indemnización a todo evento"),
                        ],
                        max_length=15,
                    ),
                ),
                ("fecha_emision", models.DateField()),
                ("vigente_desde", models.DateField()),
                (
                    "vigente_hasta",
                    models.DateField(
                        blank=True,
                        help_text="Vacío: sin término (hasta revocación).",
                        null=True,
                    ),
                ),
                ("datos", models.JSONField(default=dict)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "concepto",
                    models.ForeignKey(
                        blank=True,
                        help_text="Descuento autorizado (solo autorizaciones de descuento).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.conceptoremuneracion",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_laborales",
                        to="core.empleado",
                    ),
                ),
            ],
            options={
                "ordering": ["-vigente_desde", "-id"],
            },
        ),
        migrations.AddField(
            model_name="solicitudfirma",
            name="documento_laboral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_firma",
                to="core.documentolaboral",
            ),
        ),
    ]
