# Generated by Django 5.2.17 on 2026-09-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_documentos_laborales"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificadoemitido",
            name="anulado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificadoemitido",
            name="motivo_anulacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DATO_ERRONEO", "Contenía un dato erróneo, ya corregido"),
                    ("EMITIDO_POR_ERROR", "Se emitió por error"),
                    (
                        "RELACION_MODIFICADA",
                        "Cambiaron las condiciones que certificaba",
                    ),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
