# Generated by Django 5.2.17 on 2026-09-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_anulacion_certificados"),
    ]

    operations = [
        migrations.AddField(
            model_name="finiquito",
            name="ratificado_en",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finiquito",
            name="ratificado_via",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MI_DT", "Portal Mi DT de la Dirección del Trabajo"),
                    ("INSPECCION", "Inspector del Trabajo"),
                    ("NOTARIO", "Notario público"),
                    ("REGISTRO_CIVIL", "Oficial del Registro Civil"),
                    ("SECRETARIO_MUNICIPAL", "Secretario municipal"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="finiquito",
            name="modalidad",
            field=models.CharField(
                choices=[
                    ("PRESENCIAL", "Presencial ante ministro de fe"),
                    (
                        "ELECTRONICO",
                        "Electrónico en el portal Mi DT (voluntario para el trabajador)",
                    ),
                ],
                default="PRESENCIAL",
                max_length=15,
            ),
        ),
    ]
