# Generated by Django 5.2.17 on 2026-09-29 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_finiquito_ratificacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudfirma",
            name="emisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="firmas_emitidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitudfirma",
            name="emisor_confirmado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitudfirma",
            name="emisor_ip",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="solicitudfirma",
            name="origen",
            field=models.CharField(
                choices=[
                    ("PANEL", "Enviado por el empleador"),
                    ("PORTAL", "Solicitado por el trabajador en su portal"),
                ],
                default="PANEL",
                max_length=10,
            ),
        ),
    ]
