# Generated by Django 5.2.17 on 2026-09-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_firma_empleador_por_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="email_personal_confirmado",
            field=models.BooleanField(default=False),
        ),
    ]
