# Generated by Django 5.2.17 on 2026-09-29 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_correo_personal"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoInspeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo", models.EmailField(max_length=254)),
                ("nombre", models.CharField(max_length=150)),
                ("rut_inspector", models.CharField(max_length=12)),
                ("huella", models.CharField(max_length=64)),
                ("intentos", models.PositiveSmallIntegerField(default=0)),
                ("usado", models.BooleanField(default=False)),
                ("expira_en", models.DateTimeField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_inspeccion",
                        to="core.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RatificacionInspeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        help_text="Documento: <tipo>:<id>, como lo lista el portal.",
                        max_length=40,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("inspector_nombre", models.CharField(max_length=150)),
                ("inspector_rut", models.CharField(max_length=12)),
                ("inspector_correo", models.EmailField(max_length=254)),
                ("firma_imagen", models.TextField()),
                ("ip", models.CharField(blank=True, default="", max_length=64)),
                ("ratificado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratificaciones_inspeccion",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["-ratificado_en"],
            },
        ),
        migrations.CreateModel(
            name="RegistroInspeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo", models.EmailField(max_length=254)),
                ("nombre", models.CharField(max_length=150)),
                ("rut_inspector", models.CharField(max_length=12)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("INGRESO", "Ingreso"),
                            ("DESCARGA", "Descarga de documento"),
                            ("RATIFICACION", "Ratificación en terreno"),
                            ("SALIDA", "Salida"),
                        ],
                        max_length=15,
                    ),
                ),
                ("detalle", models.CharField(blank=True, default="", max_length=255)),
                ("ip", models.CharField(blank=True, default="", max_length=64)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_inspeccion",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
    ]
