# Generated by Django 5.2.17 on 2026-09-29 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_portal_inspeccion"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactorActualizacionSII",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField()),
                ("mes", models.PositiveSmallIntegerField()),
                ("factor", models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                "verbose_name": "factor de actualización SII",
                "verbose_name_plural": "factores de actualización SII",
                "ordering": ["-anio", "mes"],
                "unique_together": {("anio", "mes")},
            },
        ),
        migrations.CreateModel(
            name="CertificadoSueldos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField()),
                ("numero", models.PositiveIntegerField()),
                ("datos", models.JSONField(default=dict)),
                ("emitido_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados_sueldos",
                        to="core.empleado",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados_sueldos",
                        to="core.empresa",
                    ),
                ),
                (
                    "reemplaza",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reemplazado_por",
                        to="core.certificadosueldos",
                    ),
                ),
            ],
            options={
                "ordering": ["-anio", "-numero"],
                "unique_together": {("empresa", "numero")},
            },
        ),
    ]
