# Generated by Django 5.2.17 on 2026-09-29 08:00

"""Factores de actualización del año comercial 2025 (Operación Renta AT 2026), según la
tabla de corrección monetaria del SII (columna diciembre: variación del IPC de cada mes a
fin de noviembre). Los años siguientes se cargan en el admin cuando el SII los publica."""
from decimal import Decimal

from django.db import migrations

FACTORES_2025 = ['1.036', '1.026', '1.022', '1.016', '1.014', '1.012', '1.017', '1.008', '1.007', '1.003', '1.003',
                 '1.000']


def cargar(apps, schema_editor):
    Factor = apps.get_model('core', 'FactorActualizacionSII')
    for mes, factor in enumerate(FACTORES_2025, start=1):
        Factor.objects.get_or_create(anio=2025, mes=mes, defaults={'factor': Decimal(factor)})


def quitar(apps, schema_editor):
    apps.get_model('core', 'FactorActualizacionSII').objects.filter(anio=2025).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_certificado_sueldos"),
    ]

    operations = [
        migrations.RunPython(cargar, quitar),
    ]
