# Generated by Django 5.2.17 on 2026-09-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_factores_sii_2025"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="frecuencia_resumen",
            field=models.CharField(
                choices=[
                    ("DIARIA", "Cada día"),
                    ("SEMANAL", "Cada lunes"),
                    ("NUNCA", "No enviar"),
                ],
                default="SEMANAL",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="resumen_hasta",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
