# Generated by Django 5.2.17 on 2026-09-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_resumen_empleador"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="portal_invitado_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
