# Generated by Django 5.2.17 on 2026-09-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_portal_invitacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacacionempleado",
            name="horas_compensatorias",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="vacacionempleado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("VACACION_LEGAL", "Vacación Legal (Art. 67)"),
                    ("VACACION_PROGRESIVA", "Feriado Progresivo (Art. 68)"),
                    ("PERMISO_SIN_GOCE", "Permiso Sin Goce de Sueldo"),
                    (
                        "DIA_COMPENSATORIO",
                        "Día compensatorio por horas extra (Art. 32)",
                    ),
                ],
                default="VACACION_LEGAL",
                max_length=25,
            ),
        ),
    ]
