# Generated by Django 5.2.17 on 2026-09-30 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_dia_compensatorio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentolaboral",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("HORAS_EXTRA", "Pacto de horas extraordinarias"),
                    ("DESCUENTO", "Autorización de descuento"),
                    ("PERMISO_LEGAL", "Constancia de permiso legal con goce"),
                    ("INDEMNIZACION", "Pacto de indemnización a todo evento"),
                    ("REGLAMENTO", "Constancia de recepción del reglamento interno"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfirma",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("CONTRATO", "Contrato Laboral"),
                    ("ANEXO_40H", "Anexo Ley 40 Horas"),
                    ("AMONESTACION", "Carta de Amonestación"),
                    ("DESPIDO", "Carta de Despido"),
                    ("CONSTANCIA", "Constancia Laboral"),
                    ("ANEXO_CONTRATO", "Anexo de Contrato"),
                    ("LIQUIDACION", "Liquidación de Sueldo"),
                    ("VACACION", "Comprobante de Vacaciones"),
                    ("FINIQUITO", "Finiquito de Término"),
                    ("HORAS_EXTRA", "Pacto de horas extraordinarias"),
                    ("DESCUENTO", "Autorización de descuento"),
                    ("PERMISO_LEGAL", "Constancia de permiso legal"),
                    ("INDEMNIZACION", "Pacto de indemnización a todo evento"),
                    ("REGLAMENTO", "Constancia de recepción del reglamento interno"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReglamentoInterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "RIOHS",
                                "Reglamento Interno de Orden, Higiene y Seguridad",
                            ),
                            ("RIHS", "Reglamento Interno de Higiene y Seguridad"),
                        ],
                        max_length=5,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("archivo", models.FileField(upload_to="reglamentos/")),
                (
                    "publicado_en",
                    models.DateField(
                        help_text="Día en que se dio a conocer a los trabajadores."
                    ),
                ),
                ("vigente_desde", models.DateField()),
                ("remitido_dt_en", models.DateField(blank=True, null=True)),
                ("remitido_salud_en", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglamentos",
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="documentolaboral",
            name="reglamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="constancias",
                to="core.reglamentointerno",
            ),
        ),
        migrations.AddConstraint(
            model_name="reglamentointerno",
            constraint=models.UniqueConstraint(
                fields=("empresa", "version"), name="reglamento_version_unica"
            ),
        ),
    ]
