# Generated by Django 5.2.17 on 2026-09-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_reglamento_interno"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="denuncias_correo",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="empresa",
            name="denuncias_responsable",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Persona o cargo que recibe las denuncias.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="documentolaboral",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("HORAS_EXTRA", "Pacto de horas extraordinarias"),
                    ("DESCUENTO", "Autorización de descuento"),
                    ("PERMISO_LEGAL", "Constancia de permiso legal con goce"),
                    ("INDEMNIZACION", "Pacto de indemnización a todo evento"),
                    ("REGLAMENTO", "Constancia de recepción del reglamento interno"),
                    (
                        "CANALES_DENUNCIA",
                        "Constancia de información de canales de denuncia (Ley Karin)",
                    ),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfirma",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("CONTRATO", "Contrato Laboral"),
                    ("ANEXO_40H", "Anexo Ley 40 Horas"),
                    ("AMONESTACION", "Carta de Amonestación"),
                    ("DESPIDO", "Carta de Despido"),
                    ("CONSTANCIA", "Constancia Laboral"),
                    ("ANEXO_CONTRATO", "Anexo de Contrato"),
                    ("LIQUIDACION", "Liquidación de Sueldo"),
                    ("VACACION", "Comprobante de Vacaciones"),
                    ("FINIQUITO", "Finiquito de Término"),
                    ("HORAS_EXTRA", "Pacto de horas extraordinarias"),
                    ("DESCUENTO", "Autorización de descuento"),
                    ("PERMISO_LEGAL", "Constancia de permiso legal"),
                    ("INDEMNIZACION", "Pacto de indemnización a todo evento"),
                    ("REGLAMENTO", "Constancia de recepción del reglamento interno"),
                    (
                        "CANALES_DENUNCIA",
                        "Constancia de canales de denuncia (Ley Karin)",
                    ),
                ],
                max_length=20,
            ),
        ),
    ]
