# Generated by Django 5.2.17 on 2026-09-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_seguridad_laboral"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidacion",
            name="aporte_indemnizacion",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="liquidacion",
            name="tasa_indemnizacion",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
