# Generated by Django 5.2.17 on 2026-09-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_aporte_indemnizacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentolaboral",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("HORAS_EXTRA", "Pacto de horas extraordinarias"),
                    ("DESCUENTO", "Autorización de descuento"),
                    ("PERMISO_LEGAL", "Constancia de permiso legal con goce"),
                    ("INDEMNIZACION", "Pacto de indemnización a todo evento"),
                    ("REGLAMENTO", "Constancia de recepción del reglamento interno"),
                    (
                        "CANALES_DENUNCIA",
                        "Constancia de información de canales de denuncia (Ley Karin)",
                    ),
                    (
                        "ENTREGA_EPP",
                        "Constancia de entrega de elementos de protección personal",
                    ),
                    (
                        "INFORMACION_RIESGOS",
                        "Constancia de información de riesgos laborales",
                    ),
                    ("REVOCACION_DESCUENTO", "Constancia de revocación de descuento"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="solicitudfirma",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("CONTRATO", "Contrato Laboral"),
                    ("ANEXO_40H", "Anexo Ley 40 Horas"),
                    ("AMONESTACION", "Carta de Amonestación"),
                    ("DESPIDO", "Carta de Despido"),
                    ("CONSTANCIA", "Constancia Laboral"),
                    ("ANEXO_CONTRATO", "Anexo de Contrato"),
                    ("LIQUIDACION", "Liquidación de Sueldo"),
                    ("VACACION", "Comprobante de Vacaciones"),
                    ("FINIQUITO", "Finiquito de Término"),
                    ("HORAS_EXTRA", "Pacto de horas extraordinarias"),
                    ("DESCUENTO", "Autorización de descuento"),
                    ("PERMISO_LEGAL", "Constancia de permiso legal"),
                    ("INDEMNIZACION", "Pacto de indemnización a todo evento"),
                    ("REGLAMENTO", "Constancia de recepción del reglamento interno"),
                    (
                        "CANALES_DENUNCIA",
                        "Constancia de canales de denuncia (Ley Karin)",
                    ),
                    ("ENTREGA_EPP", "Constancia de entrega de EPP"),
                    ("INFORMACION_RIESGOS", "Constancia de información de riesgos"),
                    ("REVOCACION_DESCUENTO", "Constancia de revocación de descuento"),
                ],
                max_length=20,
            ),
        ),
    ]
