# Generated by Django 5.2.17 on 2026-09-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_revocacion_descuento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="encargados_karin_adicionales",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cliente",
            name="usuarios_adicionales",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
