# Generated by Django 5.2.17 on 2026-09-30 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_usuarios_adicionales"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroBitacora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_tipo",
                    models.CharField(
                        choices=[
                            ("TITULAR", "Titular de la cuenta"),
                            ("EQUIPO", "Usuario del equipo"),
                            ("SISTEMA", "Sistema"),
                        ],
                        max_length=8,
                    ),
                ),
                ("actor_nombre", models.CharField(max_length=150)),
                ("actor_rut", models.CharField(blank=True, default="", max_length=15)),
                ("accion", models.CharField(max_length=40)),
                ("descripcion", models.CharField(max_length=300)),
                ("metodo", models.CharField(blank=True, default="", max_length=8)),
                ("ruta", models.CharField(blank=True, default="", max_length=200)),
                (
                    "estado_http",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("ip", models.CharField(blank=True, default="", max_length=64)),
                ("creado_en", models.DateTimeField()),
                (
                    "hash_anterior",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("hash", models.CharField(max_length=64, unique=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones_bitacora",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bitacora",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["cuenta", "creado_en"],
                        name="core_regist_cuenta__330fe2_idx",
                    )
                ],
            },
        ),
    ]
