# Generated by Django 5.2.17 on 2026-09-30 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_bitacora"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        db_index=True, help_text="Formato 12.345.678-5.", max_length=12
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(blank=True, default="", max_length=150)),
                ("correo", models.EmailField(max_length=254)),
                ("permisos", models.JSONField(default=dict)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INVITADO", "Invitado (aún no crea su clave)"),
                            ("ACTIVO", "Activo"),
                            ("ELIMINADO", "Eliminado"),
                        ],
                        default="INVITADO",
                        max_length=10,
                    ),
                ),
                ("invitado_en", models.DateTimeField(blank=True, null=True)),
                ("activado_en", models.DateTimeField(blank=True, null=True)),
                ("eliminado_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresas",
                    models.ManyToManyField(
                        blank=True, related_name="usuarios_equipo", to="core.empresa"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuario_equipo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nombres", "apellidos"],
            },
        ),
    ]
