# Generated by Django 5.2.17 on 2026-09-30 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_usuarios_equipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportacionBitacora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(help_text="Correlativo por cuenta."),
                ),
                ("codigo", models.CharField(max_length=14, unique=True)),
                (
                    "formato",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("XLSX", "Excel")], max_length=4
                    ),
                ),
                ("desde", models.DateField(blank=True, null=True)),
                ("hasta", models.DateField(blank=True, null=True)),
                (
                    "persona",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="RUT de la persona filtrada, si hubo.",
                        max_length=15,
                    ),
                ),
                ("registros", models.PositiveIntegerField()),
                (
                    "primer_registro",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "ultimo_registro",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("huella", models.CharField(max_length=64)),
                ("generado_por_nombre", models.CharField(max_length=150)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exportaciones_bitacora",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.empresa",
                    ),
                ),
                (
                    "generado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cuenta", "numero"),
                        name="exportacion_bitacora_numero_unico",
                    )
                ],
            },
        ),
    ]
