# Generated by Django 5.2.17 on 2026-10-01 04:50

import core.cifrado
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_resumen_equipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EncargadoKarin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        db_index=True, help_text="Formato 12.345.678-5.", max_length=12
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(blank=True, default="", max_length=150)),
                ("correo", models.EmailField(max_length=254)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INVITADO", "Invitado (aún no crea su clave)"),
                            ("ACTIVO", "Activo"),
                            ("ELIMINADO", "Eliminado"),
                        ],
                        default="INVITADO",
                        max_length=10,
                    ),
                ),
                ("version_sesion", models.PositiveIntegerField(default=1)),
                ("invitado_en", models.DateTimeField(blank=True, null=True)),
                ("activado_en", models.DateTimeField(blank=True, null=True)),
                ("eliminado_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encargados_karin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresas",
                    models.ManyToManyField(
                        blank=True, related_name="encargados_karin", to="core.empresa"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encargado_karin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nombres", "apellidos"],
            },
        ),
        migrations.CreateModel(
            name="RegistroKarin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_nombre", models.CharField(max_length=150)),
                ("actor_rut", models.CharField(blank=True, default="", max_length=15)),
                ("accion", models.CharField(max_length=40)),
                ("descripcion", core.cifrado.TextoCifrado()),
                ("ip", models.CharField(blank=True, default="", max_length=64)),
                ("creado_en", models.DateTimeField()),
                (
                    "hash_anterior",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("hash", models.CharField(max_length=64, unique=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bitacora_karin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encargado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.encargadokarin",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["cuenta", "creado_en"],
                        name="core_regist_cuenta__e31968_idx",
                    )
                ],
            },
        ),
    ]
