# Generated by Django 5.2.17 on 2026-10-01 14:56

import core.cifrado
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_encargados_karin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="encargadokarin",
            name="aviso_plazos_en",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DenunciaKarin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(help_text="Correlativo por empresa."),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACOSO_SEXUAL", "Acoso sexual"),
                            ("ACOSO_LABORAL", "Acoso laboral"),
                            (
                                "VIOLENCIA",
                                "Violencia en el trabajo ejercida por terceros",
                            ),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("ESCRITA", "Por escrito"),
                            ("VERBAL", "Verbal (se levanta acta)"),
                            ("ELECTRONICA", "Por correo u otro medio electrónico"),
                        ],
                        max_length=12,
                    ),
                ),
                ("recibida_en", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RECIBIDA", "Recibida"),
                            ("INVESTIGACION", "En investigación interna"),
                            ("DERIVADA_DT", "Derivada a la Dirección del Trabajo"),
                            ("INFORME", "Informe emitido"),
                            ("REVISION_DT", "Informe en revisión de la DT"),
                            ("MEDIDAS", "Aplicar medidas"),
                            ("CERRADA", "Cerrada"),
                        ],
                        default="RECIBIDA",
                        max_length=15,
                    ),
                ),
                ("pide_derivar_dt", models.BooleanField(default=False)),
                ("datos", core.cifrado.JSONCifrado()),
                ("resguardo", core.cifrado.JSONCifrado(blank=True, null=True)),
                ("investigacion", core.cifrado.JSONCifrado(blank=True, null=True)),
                ("informe", core.cifrado.JSONCifrado(blank=True, null=True)),
                ("medidas", core.cifrado.JSONCifrado(blank=True, null=True)),
                ("hitos", models.JSONField(blank=True, default=dict)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="denuncias_karin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="denuncias_karin",
                        to="core.empresa",
                    ),
                ),
                (
                    "registrada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="denuncias_registradas",
                        to="core.encargadokarin",
                    ),
                ),
            ],
            options={
                "ordering": ["-recibida_en"],
            },
        ),
        migrations.CreateModel(
            name="ArchivoKarin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DENUNCIA_ESCRITA", "Denuncia escrita"),
                            ("ACTA_VERBAL", "Acta de denuncia verbal firmada"),
                            ("ACTA_DECLARACION", "Acta de declaración firmada"),
                            ("ANTECEDENTE", "Antecedente de la investigación"),
                            ("COMPROBANTE_DT", "Comprobante o certificado de la DT"),
                            ("PRONUNCIAMIENTO_DT", "Pronunciamiento de la DT"),
                            ("NOTIFICACION", "Comunicación o notificación firmada"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "participante",
                    models.CharField(blank=True, default="", max_length=12),
                ),
                ("nombre", core.cifrado.TextoCifrado()),
                ("clave", models.CharField(max_length=200)),
                ("tamano", models.PositiveIntegerField()),
                (
                    "huella",
                    models.CharField(
                        help_text="SHA-256 del archivo original.", max_length=64
                    ),
                ),
                ("subido_en", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.encargadokarin",
                    ),
                ),
                (
                    "denuncia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archivos",
                        to="core.denunciakarin",
                    ),
                ),
            ],
            options={
                "ordering": ["subido_en"],
            },
        ),
        migrations.AddConstraint(
            model_name="denunciakarin",
            constraint=models.UniqueConstraint(
                fields=("empresa", "numero"), name="denuncia_karin_numero_unico"
            ),
        ),
    ]
