# Generated by Django 5.2.17 on 2026-10-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_denuncias_karin"),
    ]

    operations = [
        migrations.AddField(
            model_name="denunciakarin",
            name="origen",
            field=models.CharField(
                choices=[
                    ("ENCARGADO", "Registrada por el encargado"),
                    ("PORTAL", "Ingresada por el trabajador en su portal"),
                ],
                default="ENCARGADO",
                max_length=10,
            ),
        ),
    ]
