# Generated by Django 5.2.17 on 2026-10-03 04:24

from django.db import migrations, models


def separar(apps, schema_editor):
    """Separa las direcciones escritas en un solo campo. Lo que no se puede
    separar con seguridad queda igual: la carpeta y la empresa piden completarlo."""
    from core.direcciones import desde_texto
    for modelo in ('Cliente', 'Empresa', 'Empleado'):
        Modelo = apps.get_model('core', modelo)
        for obj in Modelo.objects.exclude(direccion__isnull=True).exclude(direccion='').filter(calle='').only('id', 'direccion'):
            p = desde_texto(obj.direccion)
            if p:
                # update(): no se reescribe `direccion`, queda tal como estaba.
                Modelo.objects.filter(pk=obj.pk).update(calle=p['calle'][:200], numero=p['numero'][:30],
                                                        sin_numero=p['sin_numero'], depto=p['depto'][:30])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_normalizar_bancos"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="calle",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="cliente",
            name="depto",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Depto, oficina, casa o block.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="numero",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número, o altura/kilómetro si no tiene número.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="sin_numero",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empleado",
            name="calle",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="empleado",
            name="depto",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Depto, oficina, casa o block.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="numero",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número, o altura/kilómetro si no tiene número.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="sin_numero",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empresa",
            name="calle",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="empresa",
            name="depto",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Depto, oficina, casa o block.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="numero",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número, o altura/kilómetro si no tiene número.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="sin_numero",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(separar, migrations.RunPython.noop),
    ]
