# Generated by Django 5.2.17 on 2026-10-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0093_direccion_por_partes"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="cuidado_de",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MENOR_14", "Niño o niña menor de 14 años"),
                    (
                        "MENOR_18_DISCAPACIDAD",
                        "Adolescente menor de 18 años con discapacidad o dependencia",
                    ),
                    ("DISCAPACIDAD", "Persona con discapacidad"),
                    (
                        "DEPENDENCIA",
                        "Persona en situación de dependencia severa o moderada",
                    ),
                ],
                default="",
                help_text="Responsabilidades de cuidado no remuneradas (Ley 21.645).",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="fuero",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "MATERNIDAD",
                        "Maternidad: embarazo y hasta un año después del postnatal (Art. 201)",
                    ),
                    (
                        "POSTNATAL_PARENTAL",
                        "Padre que usa el postnatal parental (Art. 201 inc. 2°)",
                    ),
                    ("SINDICAL", "Dirigente o candidato sindical (Arts. 224, 243)"),
                    ("DELEGADO", "Delegado del personal o sindical (Arts. 229, 302)"),
                    (
                        "COMITE_PARITARIO",
                        "Representante titular del Comité Paritario (Art. 243)",
                    ),
                    ("NEGOCIACION", "Negociación colectiva en curso (Art. 309)"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="fuero_hasta",
            field=models.DateField(
                blank=True,
                help_text="Vacío: vigente sin fecha de término conocida.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="hijo_enfermedad_grave",
            field=models.BooleanField(
                default=False,
                help_text="Hijo/a menor de 18 con enfermedad grave (Ley SANNA).",
            ),
        ),
    ]
