# Generated by Django 5.2.17 on 2026-10-03 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_proteccion_trabajador"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodoVacacionesEscolares",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej.: Vacaciones de invierno 2027", max_length=80
                    ),
                ),
                ("desde", models.DateField()),
                ("hasta", models.DateField()),
                (
                    "regiones",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Vacío: todo el país. Si no, las regiones a las que aplica.",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "período de vacaciones escolares",
                "verbose_name_plural": "períodos de vacaciones escolares",
                "ordering": ["desde"],
            },
        ),
        migrations.AddField(
            model_name="empleado",
            name="fecha_parto",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SolicitudConciliacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TELETRABAJO", "Teletrabajo o trabajo a distancia"),
                            (
                                "CAMBIO_JORNADA",
                                "Cambio transitorio de turnos o jornada en vacaciones escolares",
                            ),
                        ],
                        max_length=16,
                    ),
                ),
                ("presentada_el", models.DateField()),
                (
                    "desde",
                    models.DateField(
                        blank=True,
                        help_text="Inicio propuesto (cambio de jornada).",
                        null=True,
                    ),
                ),
                ("hasta", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ACEPTADA", "Aceptada"),
                            ("ALTERNATIVA", "Se ofreció otra fórmula"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=12,
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "CARGO_NO_PERMITE",
                                "La naturaleza del cargo no permite hacerlo a distancia",
                            ),
                            (
                                "FUNCIONAMIENTO",
                                "Afecta el funcionamiento de la empresa en ese período",
                            ),
                            (
                                "TURNOS",
                                "No es posible reorganizar los turnos sin afectar a otros trabajadores",
                            ),
                            ("SEGURIDAD", "Razones de seguridad o salud en el trabajo"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "fundamento",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Circunstancias que justifican rechazar u ofrecer otra fórmula.",
                        max_length=500,
                    ),
                ),
                ("respondida_el", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_conciliacion",
                        to="core.empleado",
                    ),
                ),
            ],
            options={
                "ordering": ["-presentada_el", "-id"],
            },
        ),
    ]
