# Generated by Django 5.2.17 on 2026-10-03 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_conciliacion_y_vacaciones_escolares"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudconciliacion",
            name="cuidado_declarado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MENOR_14", "Niño o niña menor de 14 años"),
                    (
                        "MENOR_18_DISCAPACIDAD",
                        "Adolescente menor de 18 años con discapacidad o dependencia",
                    ),
                    ("DISCAPACIDAD", "Persona con discapacidad"),
                    (
                        "DEPENDENCIA",
                        "Persona en situación de dependencia severa o moderada",
                    ),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="solicitudconciliacion",
            name="origen",
            field=models.CharField(
                choices=[
                    ("PANEL", "Registrada por el empleador"),
                    ("PORTAL", "Pedida desde el portal"),
                ],
                default="PANEL",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="vacacionempleado",
            name="motivo_rechazo",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "NECESIDADES_EMPRESA",
                        "Las necesidades de la empresa no lo permiten en esas fechas",
                    ),
                    (
                        "COINCIDE_OTRO",
                        "Coincide con las vacaciones de otro trabajador del área",
                    ),
                    ("SIN_SALDO", "No tiene días suficientes"),
                    ("OTRAS_FECHAS", "Conversemos otras fechas"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="vacacionempleado",
            name="origen",
            field=models.CharField(
                choices=[
                    ("PANEL", "Registrada por el empleador"),
                    ("PORTAL", "Pedida desde el portal"),
                ],
                default="PANEL",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="vacacionempleado",
            name="respondida_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SolicitudPermiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permiso", models.CharField(max_length=30)),
                ("fecha_hecho", models.DateField()),
                ("inicio", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                (
                    "motivo_rechazo",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "FALTA_CERTIFICADO",
                                "Falta el certificado que acredita el hecho",
                            ),
                            ("YA_USADO", "Ya usó este permiso por el mismo hecho"),
                            (
                                "NO_CORRESPONDE",
                                "El permiso no corresponde a la situación informada",
                            ),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("respondida_en", models.DateTimeField(blank=True, null=True)),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_permiso",
                        to="core.documentolaboral",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_permiso",
                        to="core.empleado",
                    ),
                ),
            ],
            options={
                "ordering": ["-creada_en"],
            },
        ),
    ]
