# Generated by Django 5.2.17 on 2026-10-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_peticiones_portal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudconciliacion",
            name="motivo",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "CARGO_NO_PERMITE",
                        "La naturaleza del cargo no permite hacerlo a distancia",
                    ),
                    (
                        "FUNCIONAMIENTO",
                        "Afecta el funcionamiento de la empresa en ese período",
                    ),
                    (
                        "TURNOS",
                        "No es posible reorganizar los turnos sin afectar a otros trabajadores",
                    ),
                    ("SEGURIDAD", "Razones de seguridad o salud en el trabajo"),
                    (
                        "NO_ACREDITA_CUIDADO",
                        "No se acreditaron las responsabilidades de cuidado",
                    ),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
