# Generated by Django 5.2.17 on 2026-10-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_motivo_no_acredita_cuidado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="cuidado_de",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MENOR_14", "Niño o niña menor de 14 años"),
                    (
                        "MENOR_18_DISCAPACIDAD",
                        "Adolescente menor de 18 años con discapacidad o dependencia",
                    ),
                    ("DISCAPACIDAD", "Persona adulta (18 años o más) con discapacidad"),
                    (
                        "DEPENDENCIA",
                        "Persona adulta (18 años o más) en situación de dependencia severa o moderada",
                    ),
                ],
                default="",
                help_text="Responsabilidades de cuidado no remuneradas (Ley 21.645).",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="solicitudconciliacion",
            name="cuidado_declarado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MENOR_14", "Niño o niña menor de 14 años"),
                    (
                        "MENOR_18_DISCAPACIDAD",
                        "Adolescente menor de 18 años con discapacidad o dependencia",
                    ),
                    ("DISCAPACIDAD", "Persona adulta (18 años o más) con discapacidad"),
                    (
                        "DEPENDENCIA",
                        "Persona adulta (18 años o más) en situación de dependencia severa o moderada",
                    ),
                ],
                default="",
                max_length=24,
            ),
        ),
    ]
