# Generated by Django 5.2.17 on 2026-10-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_textos_cuidado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuentatrabajador",
            name="rut",
            field=models.CharField(
                db_index=True,
                help_text="RUT sin puntos ni guion (limpio).",
                max_length=12,
            ),
        ),
    ]
