# Generated by Django 5.2.17 on 2026-10-08 05:39

from django.db import migrations


def separar(apps, schema_editor):
    """Hasta ahora la cuenta del portal era una por RUT: si dos personas
    verificaron correos distintos del mismo RUT (el trabajador y, por ejemplo,
    un empleador que creó una ficha con ese RUT y su correo), ambas entraban a la
    misma cuenta y veían todo. Cada correo pasa a su propia cuenta.

    No se sabe quién creó la clave de una cuenta mezclada, así que se borra y
    se cierran sus sesiones: cada persona vuelve a entrar con el código a su
    correo y crea su clave si quiere. Las cuentas con un solo correo no cambian."""
    Cuenta = apps.get_model('core', 'CuentaTrabajador')
    Correo = apps.get_model('core', 'CorreoTrabajador')
    for cuenta in Cuenta.objects.all():
        correos = list(Correo.objects.filter(cuenta=cuenta).order_by('id'))
        if len(correos) < 2:
            continue
        for correo in correos[1:]:
            nueva = Cuenta.objects.create(rut=cuenta.rut)
            Correo.objects.filter(pk=correo.pk).update(cuenta=nueva)
        Cuenta.objects.filter(pk=cuenta.pk).update(password='', invitacion_clave_vista=False,
                                                   version_sesion=cuenta.version_sesion + 1)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_cuenta_trabajador_por_persona"),
    ]

    operations = [
        migrations.RunPython(separar, migrations.RunPython.noop),
    ]
