# Generated by Django 5.2.17 on 2026-10-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0100_separar_cuentas_mezcladas"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpfirma",
            name="codigo_hash",
            field=models.CharField(default="", max_length=64),
        ),
    ]
