# Generated by Django 5.2.17 on 2026-10-08 06:10

import hashlib
import hmac

from django.conf import settings
from django.db import migrations


def huellas(apps, schema_editor):
    """Los códigos ya enviados pasan a huella antes de borrar el texto plano, así
    quien tenía uno vigente al publicar puede seguir usándolo (duran 10 minutos)."""
    OTPFirma = apps.get_model('core', 'OTPFirma')
    clave = settings.SECRET_KEY.encode()
    for otp in OTPFirma.objects.exclude(codigo='').select_related('solicitud'):
        mensaje = f'firma:{otp.solicitud.token}:{otp.codigo}'.encode()
        OTPFirma.objects.filter(pk=otp.pk).update(
            codigo_hash=hmac.new(clave, mensaje, hashlib.sha256).hexdigest(), codigo='')


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0101_otpfirma_codigo_hash"),
    ]

    operations = [
        migrations.RunPython(huellas, migrations.RunPython.noop),
    ]
