# Generated by Django 5.2.17 on 2026-10-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_otpfirma_huella_de_codigos_vivos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpfirma",
            name="codigo",
        ),
    ]
