# Generated by Django 5.2.17 on 2026-10-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0103_otpfirma_sin_codigo_en_texto"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudfirma",
            name="intentos_clave",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="solicitudfirma",
            name="ultimo_intento_clave",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitudfirma",
            name="verificacion",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "CODIGO_CORREO",
                        "Código de un solo uso enviado a su correo personal",
                    ),
                    ("CLAVE_PORTAL", "Clave personal del portal del trabajador"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
